//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrinter.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.Linq;
    
    public partial class ColorUnit
    {
        private PrinterStockEntities db = new PrinterStockEntities();

        public int id { get; set; }
        public string colorunit { get; set; }

        public static IEnumerable<SelectListItem> GetColor
        {
            get
            {
                PrinterStockEntities db = new PrinterStockEntities();
                var allJobs = db.ColorUnits.OrderBy(f => f.id).Select(f => new SelectListItem
                {
                    Value = f.id.ToString(),
                    Text = f.colorunit
                }).ToList();
                return allJobs;
            }
        }
    }
}
