//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrinter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.Linq;
    
    public partial class Customer
    {
        private PrinterStockEntities db = new PrinterStockEntities();

        public int id { get; set; }

        [Display(Name = "บริษัท")]
        public string company { get; set; }

        [Display(Name = "ชื่อ")]
        [Required(ErrorMessage="กรุณากรอกชื่อ")]
        public string fname { get; set; }

        [Display(Name = "นามสกุล")]
        [Required(ErrorMessage = "กรุณากรอกนามสกุล")]
        public string lname { get; set; }

        public string name { get; set; }

        [Display(Name = "โทรศัพท์มือถือ")]
        [Phone(ErrorMessage="รูปแบบเบอร์โทรศัพท์ไม่ถูกต้อง")]
        public string mobile { get; set; }

        [Display(Name = "โทรศัพท์บ้าน")]
        public string phone { get; set; }

        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage="รูปแบบ Email ไม่ถูกต้อง")]
        public string email { get; set; }

        [Display(Name = "ที่อยู่")]
        public string address { get; set; }

        [Display(Name = "จังหวัด")]
        public Nullable<int> id_province { get; set; }

        [Display(Name = "รหัสไปรษณีย์")]
        [RegularExpression(@"^\d+$", ErrorMessage = "ระบุเป็นตัวเลข")]
        public Nullable<short> postcode { get; set; }

        [Display(Name = "Fax")]
        [Phone(ErrorMessage = "รูปแบบเบอร์แฟกซ์ไม่ถูกต้อง")]
        public string fax { get; set; }

        public IEnumerable<SelectListItem> ProvinceItems
        {            
            get
            {
                var allFlavors = db.Provinces.OrderBy(f => f.id).Select(f => new SelectListItem
                {
                    Value = f.id.ToString(),
                    Text = f.province_name
                });
                return DefaultProvnceItem.Concat(allFlavors);                
            }
        }
 
        public IEnumerable<SelectListItem> DefaultProvnceItem
        {
            get { return Enumerable.Repeat(new SelectListItem
            {
                Value = "0", Text = "-- เลือกจังหวัด --"
            }, count: 1); }
        }
    }
}
