//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadDataPrinter
    {
        public HeadDataPrinter()
        {
            this.DetailDataPrinters = new HashSet<DetailDataPrinter>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<int> id_owner { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> totalvat { get; set; }
        public Nullable<double> totaldiscount { get; set; }
        public Nullable<double> totalprice { get; set; }
        public Nullable<double> grandtotalprice { get; set; }
        public Nullable<int> changedbyid { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> changedate { get; set; }
    
        public virtual ICollection<DetailDataPrinter> DetailDataPrinters { get; set; }
    }
}
