//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrinter.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.Linq;
    
    public partial class Job_Type
    {
        public int id { get; set; }
        public string name_job_type { get; set; }

        public IEnumerable<SelectListItem> JobTypeItems
        {
            get
            {
                PrinterStockEntities db = new PrinterStockEntities();
                var allJobs = db.Job_Type.OrderBy(f => f.id).Select(f => new SelectListItem
                {
                    Value = f.id.ToString(),
                    Text = f.name_job_type
                }).ToList();
                return allJobs;
            }
        }
    }
}
