//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrinter.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.Linq;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Machine_Printer
    {
        [Display(Name = "No.")]
        public string id { get; set; }

        [Display(Name = "Name")]
        public string name_printer { get; set; }

        [Display(Name = "System")]
        public Nullable<int> system_id { get; set; }

        [Display(Name = "Color Unit")]
        public Nullable<int> colorunit_id { get; set; }

        [Display(Name = "กว้าง")]
        public Nullable<double> paper_width { get; set; }

        [Display(Name = "ยาว")]
        public Nullable<double> paper_length { get; set; }

        [Display(Name = "แกรม")]
        public double graeme_print { get; set; }

        [Display(Name = "ซ้าย")]
        public Nullable<double> paper_left { get; set; }

        [Display(Name = "ขวา")]
        public Nullable<double> paper_right { get; set; }

        [Display(Name = "บน")]
        public Nullable<double> paper_top { get; set; }

        [Display(Name = "ล่าง")]
        public Nullable<double> paper_under { get; set; }

        [Display(Name = "Auto Duplex")]
        public Nullable<double> autoduplex_gsm { get; set; }

        [Display(Name = "ความเร็วรอบพิมพ์สี")]
        public Nullable<double> printingspeed_color { get; set; }

        [Display(Name = "ความเร็วรอบพิมพ์ขาวดำ")]
        public Nullable<double> printingspeed_blackwhite { get; set; }
  
        [Display(Name = "Color meter")]
        public Nullable<double> colormeter_price { get; set; }

        [Display(Name = "BW meter")]
        public Nullable<double> blackwhitemeter_price { get; set; }

        [Display(Name = "เผื่อในการตั้งเครื่องหน้า 1")]
        public Nullable<double> setprintpang1 { get; set; }

        [Display(Name = "เผื่อในการตั้งเครื่องหน้า 2")]
        public Nullable<double> setprintpang2 { get; set; }

        [Display(Name = "ค่าเสื่อมราคาเรื่อง (ราคาเครื่อง)")]
        public Nullable<double> printercostprict { get; set; }

        [Display(Name = "ระยะผ่อน(เดือน)")]
        public Nullable<double> installment { get; set; }

        [Display(Name = "ค่าแรงงาน")]
        public Nullable<double> @operator { get; set; }

        [Display(Name = "ชั่วโมงในการทำงาน")]
        public Nullable<double> workinghours { get; set; }

        [Display(Name = "ค่าไฟฟ้า")]
        public Nullable<double> electricity { get; set; }

        public IEnumerable<SelectListItem> PrinterItems
        {
            get
            {
                PrinterStockEntities db = new PrinterStockEntities();
                var allJobs = db.Machine_Printer.OrderBy(f => f.id).Select(f => new SelectListItem
                {
                    Value = f.id.ToString(),
                    Text = f.name_printer
                }).ToList();
                return allJobs;
            }
        }
    }

    public class TempPrinterResult
    {
        
        [Display(Name = "No.")]
        public string id { get; set; }

        [Display(Name = "Name")]
        public string name_printer { get; set; }

        [Display(Name = "System Name")]
        public string systemname { get; set; }

        [Display(Name = "System")]
        public Nullable<int> system_id { get; set; }

        [Display(Name = "Color Unit")]
        public Nullable<int> colorunit_id { get; set; }

        [Display(Name = "Color")]
        public string colorunit { get; set; }

        [Display(Name = "กว้าง")]
        public Nullable<double> paper_width { get; set; }

        [Display(Name = "ยาว")]
        public Nullable<double> paper_length { get; set; }

        [Display(Name = "แกรม")]
        public double graeme_print { get; set; }

        [Display(Name = "ซ้าย")]
        public Nullable<double> paper_left { get; set; }

        [Display(Name = "ขวา")]
        public Nullable<double> paper_right { get; set; }

        [Display(Name = "บน")]
        public Nullable<double> paper_top { get; set; }

        [Display(Name = "ล่าง")]
        public Nullable<double> paper_under { get; set; }

        [Display(Name = "Auto Duplex")]
        public Nullable<double> autoduplex_gsm { get; set; }

        [Display(Name = "ความเร็วรอบพิมพ์สี")]
        public Nullable<double> printingspeed_color { get; set; }

        [Display(Name = "ความเร็วรอบพิมพ์ขาวดำ")]
        public Nullable<double> printingspeed_blackwhite { get; set; }
  
        [Display(Name = "Color meter")]
        public Nullable<double> colormeter_price { get; set; }

        [Display(Name = "BW meter")]
        public Nullable<double> blackwhitemeter_price { get; set; }

        [Display(Name = "เผื่อในการตั้งเครื่องหน้า 1")]
        public Nullable<double> setprintpang1 { get; set; }

        [Display(Name = "เผื่อในการตั้งเครื่องหน้า 2")]
        public Nullable<double> setprintpang2 { get; set; }

        [Display(Name = "ค่าเสื่อมราคาเรื่อง (ราคาเครื่อง)")]
        public Nullable<double> printercostprict { get; set; }

        [Display(Name = "ระยะผ่อน(เดือน)")]
        public Nullable<double> installment { get; set; }

        [Display(Name = "ค่าแรงงาน")]
        public Nullable<double> @operator { get; set; }

        [Display(Name = "ชั่วโมงในการทำงาน")]
        public Nullable<double> workinghours { get; set; }

        [Display(Name = "ค่าไฟฟ้า")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> electricity { get; set; }
        
    }

    public partial class EditCreatePrinter
    {
        public EditCreatePrinter() { }

        public Machine_Printer EditCreatePrinterModel(EditCreatePrinter e)
        {
            Machine_Printer m = new Machine_Printer();
            m.id = e.id;
            m.autoduplex_gsm = e.autoduplex_gsm;
            m.blackwhitemeter_price = e.blackwhitemeter_price;
            m.colormeter_price = e.colormeter_price;
            m.colorunit_id = e.colorunit_id;
            m.graeme_print = e.graeme_print;
            m.installment = e.installment;
            m.name_printer = e.name_printer;
            m.@operator = e.@operator;
            m.paper_left = e.paper_left;
            m.paper_length = e.paper_length;
            m.paper_right = e.paper_right;
            m.paper_top = e.paper_top;
            m.paper_under = e.paper_under;
            m.paper_width = e.paper_width;
            m.printercostprict = e.printercostprict;
            m.printingspeed_blackwhite = e.printingspeed_blackwhite;
            m.printingspeed_color = e.printingspeed_color;
            m.setprintpang1 = e.setprintpang1;
            m.setprintpang2 = e.setprintpang2;
            m.system_id = e.system_id;
            m.workinghours = e.workinghours;
            return m;
        }

        [Display(Name = "No.")]
        [Required(ErrorMessage = "กรุณาระบุเลข No")]
        [Remote("CheckDuplicateID", "Printer", HttpMethod = "POST", ErrorMessage = "เลข No. นี้มีในระบบแล้ว")]
        public string id { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "กรุณาระบุชื่อเครื่องพิมพ์")]
        public string name_printer { get; set; }

        [Display(Name = "System")]
        [RegularExpression(@"^\d+$", ErrorMessage = "ระบุเป็นตัวเลข")]
        public Nullable<int> system_id { get; set; }

        [Display(Name = "Color Unit")]
        [RegularExpression(@"^\d+$", ErrorMessage = "ระบุเป็นตัวเลข")]
        public Nullable<int> colorunit_id { get; set; }

        [Display(Name = "กว้าง")]
        [Required(ErrorMessage = "กรุณาระบุความกว้างกระดาษ")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> paper_width { get; set; }

        [Display(Name = "ยาว")]
        [Required(ErrorMessage = "กรุณาระบุความยาวกระดาษ")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> paper_length { get; set; }

        [Display(Name = "แกรม")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public double graeme_print { get; set; }

        [Display(Name = "ซ้าย")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> paper_left { get; set; }

        [Display(Name = "ขวา")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> paper_right { get; set; }

        [Display(Name = "บน")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> paper_top { get; set; }

        [Display(Name = "ล่าง")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> paper_under { get; set; }

        [Display(Name = "Auto Duplex")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> autoduplex_gsm { get; set; }

        [Display(Name = "ความเร็วรอบพิมพ์สี")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> printingspeed_color { get; set; }

        [Display(Name = "ความเร็วรอบพิมพ์ขาวดำ")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> printingspeed_blackwhite { get; set; }

        [Display(Name = "Color meter")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> colormeter_price { get; set; }

        [Display(Name = "BW meter")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> blackwhitemeter_price { get; set; }

        [Display(Name = "เผื่อในการตั้งเครื่องหน้า 1")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> setprintpang1 { get; set; }

        [Display(Name = "เผื่อในการตั้งเครื่องหน้า 2")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> setprintpang2 { get; set; }

        [Display(Name = "ค่าเสื่อมราคาเรื่อง (ราคาเครื่อง)")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> printercostprict { get; set; }

        [Display(Name = "ระยะผ่อน(เดือน)")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> installment { get; set; }

        [Display(Name = "ค่าแรงงาน")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> @operator { get; set; }

        [Display(Name = "ชั่วโมงในการทำงาน")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> workinghours { get; set; }

        [Display(Name = "ค่าไฟฟ้า")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> electricity { get; set; }
        

        public IEnumerable<SelectListItem> PrinterItems
        {
            get
            {
                PrinterStockEntities db = new PrinterStockEntities();
                var allJobs = db.Machine_Printer.OrderBy(f => f.id).Select(f => new SelectListItem
                {
                    Value = f.id.ToString(),
                    Text = f.name_printer
                }).ToList();
                return allJobs;
            }
        }
    }
}
