//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrinter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Owner
    {
        public int id { get; set; }

        [Display(Name="ชื่อ")]
        public string firstname { get; set; }

        [Display(Name = "นามสกุล")]
        public string lastname { get; set; }
        
        public Nullable<System.DateTime> createrdate { get; set; }

        public string name {
            get {
                return firstname + " " + lastname;
            } 
        }

        [Display(Name = "Username")]
        public string username { get; set; }

        [Display(Name = "Password")]
        public string password { get; set; }

        [Display(Name = "Role")]
        public string roles { get; set; }

        [Display(Name = "Email")]
        public string email { get; set; }

        public SelectList dp
        {
            get
            {
                return new SelectList(new List<Object>{ 
                       new { value = "" , text = "-- เลือก Role--"  },
                       new { value = "Admin" , text = "Admin" },
                       new { value = "User" , text = "User"}
                    },
                  "value", "text", this.roles);
            }
        }
    }

    public class LogOnModel
    {
        [Required]
        public string username { get; set; }

        [Required]
        public string password { get; set; }
    }

    public class EditUserModel
    {
        public EditUserModel() { }

        public Owner EditUserModelOwner(EditUserModel model)
        {
            Owner o = new Owner();
            o.id = model.id;
            o.firstname = model.firstname;
            o.lastname = model.lastname;
            o.username = model.username;
            o.password = model.password;
            o.roles = model.roles;
            o.email = model.email;
            o.createrdate = DateTime.Now;
            return o;
        }

        public int id { get; set; }

        [Required(ErrorMessage = "กรุณากรอกชื่อ")]
        public string firstname { get; set; }

        [Required(ErrorMessage = "กรุณากรอกนามสกุล")]
        public string lastname { get; set; }

        public Nullable<System.DateTime> createrdate { get; set; }

        public string username { get; set; }

        public string password { get; set; }

        [Required(ErrorMessage = "กรุณาระบุ Role")]
        public string roles { get; set; }

        [EmailAddress]
        public string email { get; set; }
    }

    public class CreateUserModel
    {
        public CreateUserModel() { }

        public Owner CreateUserModelOwner(CreateUserModel model)
        { 
            Owner o = new Owner();
            o.id = model.id;
            o.firstname = model.firstname;
            o.lastname = model.lastname;
            o.username = model.username;
            o.password = model.password;
            o.roles = model.roles;
            o.email = model.email;
            o.createrdate = DateTime.Now;
            return o;
        }

        public int id { get; set; }
        
        [Required(ErrorMessage="กรุณากรอกชื่อ")]
        public string firstname { get; set; }

        [Required(ErrorMessage = "กรุณากรอกนามสกุล")]
        public string lastname { get; set; }

        public Nullable<System.DateTime> createrdate { get; set; }

        [Required(ErrorMessage = "กรุณากรอก Username")]
        [Remote("CheckDuplicateUser", "Owner", HttpMethod = "POST", ErrorMessage = "Username นี้มีในระบบแล้ว")]
        public string username { get; set; }

        [Required(ErrorMessage = "กรุณากรอก Password")]
        public string password { get; set; }

        [Required(ErrorMessage = "กรุณาระบุ Role")]
        public string roles { get; set; }
        
        [EmailAddress]
        public string email { get; set; }

        public SelectList dp
        {
            get
            {
                return new SelectList(new List<Object>{ 
                       new { value = "" , text = "-- เลือก Role--"  },
                       new { value = "Admin" , text = "Admin" },
                       new { value = "User" , text = "User"}
                    },
                  "value", "text", this.roles);
            }
        }
    }
}
