//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrinter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.Linq;
    
    public partial class Stock_Paper
    {
        [Display(Name="No.")]
        public string id { get; set; }

        [Display(Name = "Type Paper")]
        public string type_paper { get; set; }

        [Display(Name = "GSM")]
        public Nullable<int> gsm { get; set; }

        [Display(Name = "Width")]
        public Nullable<double> width { get; set; }

        [Display(Name = "Length")]
        public Nullable<double> length { get; set; }

        [Display(Name = "Sheets/Pack")]
        public Nullable<double> sheets_per_pack { get; set; }

        [Display(Name = "Price/Pack")]
        public Nullable<double> price_per_pack { get; set; }

        [Display(Name = "Price/Sheet")]
        public Nullable<double> price_per_sheet { get; set; }

        public Dictionary<string, List<double?>> IdandSize 
        {
            get { 
                Dictionary<string, List<double?>> x = new Dictionary<string, List<double?>>();
                foreach (Stock_Paper c in _papers)
                {
                    List<double?> list = new List<double?>();
                    list.Add(c.width);
                    list.Add(c.length);
                    list.Add(c.gsm);
                    x.Add(c.id, list);
                }
                return x;
            }
        }

        private List<Stock_Paper> _papers;

        public IEnumerable<SelectListItem> PaperItems
        {
            get
            {
                PrinterStockEntities db = new PrinterStockEntities();
                this._papers = db.Stock_Paper.OrderBy(f => f.id).ToList();

                var all = _papers.OrderBy(f => f.id).Select(f => new SelectListItem
                {
                    Value = f.id.ToString(),
                    Text = f.type_paper
                }).ToList();
                return all;
            }
        }
    }

    public class EditPaperModel
    {
        public EditPaperModel() { }

        public Stock_Paper EditPaperModelStock(EditPaperModel model)
        {
            Stock_Paper s = new Stock_Paper();
            s.gsm = model.gsm;
            s.id = model.id;
            s.length = model.length;
            s.price_per_pack = model.price_per_pack;
            s.price_per_sheet = model.price_per_sheet;
            s.sheets_per_pack = model.sheets_per_pack;
            s.type_paper = model.type_paper;
            s.width = model.width;
            return s;
        }

        [Display(Name = "No.")]
        public string id { get; set; }

        [Display(Name = "Type Paper")]
        [Required(ErrorMessage="กรุณาระบุประเภทกระดาษ")]
        public string type_paper { get; set; }

        [Display(Name = "GSM")]
        [Required(ErrorMessage="กรุณาระบุขนาดแกรม")]
        [RegularExpression(@"^\d+$", ErrorMessage = "ระบุเป็นตัวเลข")]
        public Nullable<int> gsm { get; set; }

        [Display(Name = "Width")]
        [Required(ErrorMessage="กรุณาระบุความกว้าง")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> width { get; set; }

        [Display(Name = "Length")]
        [Required(ErrorMessage = "กรุณาระบุความยาว")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> length { get; set; }

        [Display(Name = "Sheets/Pack")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> sheets_per_pack { get; set; }

        [Display(Name = "Price/Pack")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> price_per_pack { get; set; }

        [Display(Name = "Price/Sheet")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> price_per_sheet { get; set; }
    }

    public class CreatePaperModel
    {
        public CreatePaperModel() { }

        public Stock_Paper CreatePaperModelStock(CreatePaperModel model)
        {
            Stock_Paper s = new Stock_Paper();
            s.gsm = model.gsm;
            s.id = model.id;
            s.length = model.length;
            s.price_per_pack = model.price_per_pack;
            s.price_per_sheet = model.price_per_sheet;
            s.sheets_per_pack = model.sheets_per_pack;
            s.type_paper = model.type_paper;
            s.width = model.width;
            return s;
        }

        [Display(Name = "No.")]
        [Required(ErrorMessage="กรุณาระบุหมายเลขรหัส")]
        [Remote("CheckDuplicateNo", "StockPaper", HttpMethod = "POST", ErrorMessage = "เลข No. นี้มีในระบบแล้ว")]
        public string id { get; set; }

        [Display(Name = "Type Paper")]
        [Required(ErrorMessage = "กรุณาระบุประเภทกระดาษ")]
        public string type_paper { get; set; }

        [Display(Name = "GSM")]
        [Required(ErrorMessage = "กรุณาระบุขนาดแกรม")]
        [RegularExpression(@"^\d+$", ErrorMessage = "ระบุเป็นตัวเลข")]
        public Nullable<int> gsm { get; set; }

        [Display(Name = "Width")]
        [Required(ErrorMessage = "กรุณาระบุความกว้าง")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> width { get; set; }

        [Display(Name = "Length")]
        [Required(ErrorMessage = "กรุณาระบุความยาว")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> length { get; set; }

        [Display(Name = "Sheets/Pack")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> sheets_per_pack { get; set; }

        [Display(Name = "Price/Pack")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> price_per_pack { get; set; }

        [Display(Name = "Price/Sheet")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "ระบุเป็นตัวเลข หรือทศนิยม")]
        public Nullable<double> price_per_sheet { get; set; }
    }
}
