//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrinter.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.Linq;
    
    public partial class Sys_Print
    {
        private static PrinterStockEntities db = new PrinterStockEntities();

        public int id { get; set; }
        public string systemname { get; set; }

        public static IEnumerable<SelectListItem> GetTypeSys
        {
            get
            {
                var allFlavors = db.Sys_Print.OrderBy(f => f.id).Select(f => new SelectListItem
                {
                    Value = f.id.ToString(),
                    Text = f.systemname
                });
                return allFlavors;
            }
        }
    }
}
